import { colorById } from '../data/colors.js';

const money = (n) => n.toLocaleString('en-CA', { style: 'currency', currency: 'CAD' });

export function buildEstimateText({ brand, house, roofProduct, roofColorId, roofProfile, wallProduct, wallColorId, wallProfile, estimate }) {
  const roofColor = colorById(roofColorId);
  const wallColor = colorById(wallColorId);
  const lines = [];
  lines.push(`${brand.name} — Design & Estimate Summary`);
  lines.push(brand.tagline);
  lines.push('='.repeat(50));
  lines.push('');
  lines.push(`Job: ${house.jobNumber}`);
  lines.push(`Customer: ${house.customerName}`);
  lines.push(`Address: ${house.address}`);
  lines.push(`Date: ${new Date().toLocaleDateString('en-CA')}`);
  lines.push('');
  lines.push('SELECTIONS');
  lines.push('-'.repeat(50));
  lines.push(`Roof material: ${roofProduct.label} (${roofProfile || 'standard profile'})`);
  lines.push(`Roof color: ${roofColor.code} — ${roofColor.name}`);
  lines.push(`Siding material: ${wallProduct.label} (${wallProfile || 'standard profile'})`);
  lines.push(`Siding color: ${wallColor.code} — ${wallColor.name}`);
  lines.push('');
  lines.push('PRICE BREAKDOWN');
  lines.push('-'.repeat(50));
  estimate.lineItems.forEach((li) => {
    lines.push(`${li.label.padEnd(46)} ${li.qty.toLocaleString()} ${li.unit}  ${money(li.total)}`);
  });
  lines.push('-'.repeat(50));
  lines.push(`Subtotal: ${money(estimate.subtotal)}`);
  if (estimate.deals.fullWrap) {
    lines.push(`Full Wrap discount (7%): -${money(estimate.deals.fullWrapDiscountAmount)}`);
  }
  if (estimate.manualDiscount > 0) {
    lines.push(`Additional discount: -${money(estimate.manualDiscount)}`);
  }
  lines.push(`Pre-tax total: ${money(estimate.preTaxTotal)}`);
  lines.push(`GST (${(estimate.gstRate * 100).toFixed(0)}%): ${money(estimate.gst)}`);
  lines.push(`TOTAL ESTIMATE: ${money(estimate.total)}`);
  lines.push('');
  lines.push('This is a preliminary estimate generated by the IronWrap 3D Configurator.');
  lines.push('Final pricing subject to on-site verification and signed contract.');
  return lines.join('\n');
}

export function downloadTextFile(filename, text) {
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
